FROM nginx:stable

RUN apt-get update -qq

# include nginx configuration
COPY nginx.dev.conf /etc/nginx/nginx.conf

# sets command prompt look
ENV PS1="\[\e[0;33m\]\u\[\e[0;36m\]@\[\e[0;36m\]\h \[\e[0;37m\]\w \[\e[0;33m\]$ \[\e[0m\]"

# does not actually publish the port;
# it functions as a type of documentation between the person who builds the image
# and the person who runs the container
EXPOSE 5555