version: "3"

services:
  mps_backend_nginx:
    build:
      context: .
      dockerfile: Dockerfile.live
    image: gcr.io/mps-project2-backend/nginx:v1
    container_name: mps-backend-nginx-live
    hostname: nginx
    stdin_open: true
    tty: true
