version: "3.5"

services:
  backend_nodjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: mps_backend/python
    container_name: mps_backend_python_dev
    hostname: dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/data/mps
      - /data/mps/node_modules # prevents node_modules folder to be shared
    # runs private.js and prevent 'node private.js' process to have id 1 inside the container
    entrypoint: ["dumb-init", "python", "src/server.py"]

networks:
  default:
    name: mps_backend_python_live