version: "3.5"

services:
  backend_nodjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: mps_backend/nodejs
    container_name: mps_backend_nodejs_live
    hostname: live
    stdin_open: true
    tty: true
    # runs private.js and prevent 'node private.js' process to have id 1 inside the container
    entrypoint: ["dumb-init", "node", "src/server.js"]

networks:
  default:
    name: mps_backend_nodejs_live