version: "3"

services:
  mps_backend_nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/mps-project2-backend/nodejs:latest
    container_name: mps-backend-nodejs-live
    hostname: live
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production
