apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./nodejs/docker-compose.live.yml convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mps-backend-nodejs
  name: mps-backend-nodejs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mps-backend-nodejs
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
        - image: gcr.io/mps-project2-backend/nodejs:latest
          imagePullPolicy: Always
          name: mps-backend-nodejs-live
          resources: {}
          stdin: true
          tty: true
      hostname: live
      restartPolicy: Always